---
version: "3"
services:
  database:
    image: mongo
  application:
    image: bookmanager_app
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/app/backend
      - ./frontend:/var/app/frontend
    ports:
      - "10000:10000"
    depends_on:
      - "database"
    environment:
      - GR_KEY=64XpDYVZdQRi66f7Ev6xQw
